# This config file contains the fields for the config dictionary required by the
# Converter class.
#
# DB_NAME_<DB_TYPE>
#   db: name of the database
#   db_type: (PHY or BGC)
#   input_path: path with original files to convert
#   outdir_pq: destination path for parquet version
#   outdir_schema: destination path for the schema of the parquet version
#   fname_pq: basename for the parquet file (e.g. 'filename' would generate 'filename_XXX.parquet' files)
#   add_derived_vars: True to add derived variables (absolute salinity, conservative temperature, sigma1)
#   overwrite: True to overwrite any pre-existing parquet dataset in outdir_pq
#   tmp_path: folder for temporary files (not required by all converters)
#   ln_path: path to symbolic links to generate CrocoLake (required only when generating CrocoLake with CrocoLakeLoader)


# CROCOLAKE
CROCOLAKE_PHY:
  db: CROCOLAKE
  db_type: PHY
  outdir_pq: /vortexfs1/share/boom/users/enrico.milanese/myDatabases/0007_PHY_CROCOLAKE-QC-MERGED/current/
  fname_pq: 0007_PHY_CROCOLAKE
  ln_path: /vortexfs1/share/boom/users/enrico.milanese/myDatabases/0003_PHY_CROCOLAKE-QC/current/

CROCOLAKE_BGC:
  db: CROCOLAKE
  db_type: BGC
  outdir_pq: /vortexfs1/share/boom/users/enrico.milanese/myDatabases/0007_BGC_CROCOLAKE-QC-MERGED/current/
  fname_pq: 0007_BGC_CROCOLAKE
  ln_path: /vortexfs1/share/boom/users/enrico.milanese/myDatabases/0003_BGC_CROCOLAKE-QC/current/

# Argo QC
ARGO_PHY:
  db: ARGO
  db_type: PHY
  db_codename: ARGO
  input_path: /vortexfs1/share/boom/users/enrico.milanese/myDatabases/1011_PHY_ARGO-CLOUD/current
  outdir_pq: /vortexfs1/share/boom/users/enrico.milanese/myDatabases/1003_PHY_ARGO-QC/current/
  outdir_schema: ./schema/
  fname_pq: 1003_ARGO-QC_PHY
  add_derived_vars: True
  overwrite: True
  tmp_path:

ARGO_BGC:
  db: ARGO
  db_type: BGC
  db_codename: ARGO
  input_path: /vortexfs1/share/boom/users/enrico.milanese/myDatabases/1011_BGC_ARGO-CLOUD/current
  outdir_pq: /vortexfs1/share/boom/users/enrico.milanese/myDatabases/1003_BGC_ARGO-QC/current/
  outdir_schema: ./schema/
  fname_pq: 1003_ARGO-QC_BGC
  add_derived_vars: True
  overwrite: True
  tmp_path:

# Argo GDAC
ARGO-GDAC_PHY:
  db: ARGO-GDAC
  db_type: PHY
  input_path: /proj/boom/users/enrico.milanese/crocolaketools-public-fork/data/GDAC/dac/
  outdir_pq: /vortexfs1/share/boom/users/enrico.milanese/myDatabases/1011_PHY_ARGO-CLOUD/current/

ARGO-GDAC_BGC:
  db: ARGO-GDAC
  db_type: BGC
  input_path: /proj/boom/users/enrico.milanese/crocolaketools-public-fork/data/GDAC/dac/
  outdir_pq: /vortexfs1/share/boom/users/enrico.milanese/myDatabases/1011_BGC_ARGO-CLOUD/current/

# GLODAP config
GLODAP_PHY:
  db: GLODAP
  db_type: PHY
  db_codename: GLODAP
  input_path: /vortexfs1/share/boom/users/enrico.milanese/originalDatabases/GLODAP/v3.2026/
  outdir_pq: /vortexfs1/share/boom/users/enrico.milanese/myDatabases/1101_PHY_GLODAP/current/
  outdir_schema: ./schema/
  fname_pq: 1101_GLODAP_PHY
  add_derived_vars: True
  overwrite: True
  tmp_path:

GLODAP_BGC:
  db: GLODAP
  db_type: BGC
  db_codename: GLODAP
  input_path: /vortexfs1/share/boom/users/enrico.milanese/originalDatabases/GLODAP/v3.2026/
  outdir_pq: /vortexfs1/share/boom/users/enrico.milanese/myDatabases/1101_BGC_GLODAP/current/
  outdir_schema: ./schema/
  fname_pq: 1101_GLODAP_BGC
  add_derived_vars: True
  overwrite: True
  tmp_path:

# SPOTS
SPOTS_PHY:
  db: SPOTS
  db_type: PHY
  input_path: /vortexfs1/share/boom/users/enrico.milanese/originalDatabases/SPOTS/
  outdir_pq: /vortexfs1/share/boom/users/enrico.milanese/myDatabases/1501_PHY_SPOTS/current/
  outdir_schema: ./schemas/SPOTS/
  fname_pq: demo_SPOTS_PHY
  add_derived_vars: True
  overwrite: True
  tmp_path:

SPOTS_BGC:
  db: SPOTS
  db_type: BGC
  input_path: /vortexfs1/share/boom/users/enrico.milanese/originalDatabases/SPOTS/
  outdir_pq: /vortexfs1/share/boom/users/enrico.milanese/myDatabases/1501_BGC_SPOTS/current/
  outdir_schema: ./schemas/SPOTS/
  fname_pq: demo_SPOTS_BGC
  add_derived_vars: True
  overwrite: True
  tmp_path:

# Spray Gliders
SprayGliders_PHY:
  db: SprayGliders
  db_type: PHY
  db_codename: SPRAY
  input_path: /vortexfs1/share/boom/users/enrico.milanese/originalDatabases/SprayGliders/
  outdir_pq: /vortexfs1/share/boom/users/enrico.milanese/myDatabases/1201_PHY_SPRAY/current/
  outdir_schema: ./schemas/
  fname_pq: 1201_SPRAY_PHY
  add_derived_vars: True
  overwrite: True
  tmp_path: /vortexfs1/share/boom/users/enrico.milanese/tmp_spray_phy/

SprayGliders_BGC:
  db: SprayGliders
  db_type: BGC
  db_codename: SPRAY
  input_path: /vortexfs1/share/boom/users/enrico.milanese/originalDatabases/SprayGliders/
  outdir_pq: /vortexfs1/share/boom/users/enrico.milanese/myDatabases/1201_BGC_SPRAY/current/
  outdir_schema: ./schemas/
  fname_pq: 1201_SPRAY_BGC
  add_derived_vars: True
  overwrite: True
  tmp_path: /vortexfs1/share/boom/users/enrico.milanese/tmp_spray_bgc/

# Saildrones
Saildrones_PHY:
  db: Saildrones
  db_type: PHY
  db_codename: SAILDRONES
  input_path: /vortexfs1/share/boom/users/enrico.milanese/originalDatabases/Saildrones/
  outdir_pq: /vortexfs1/share/boom/users/enrico.milanese/myDatabases/1300_PHY_SAILDRONES/current/
  outdir_schema: ./schemas/Saildrones/
  fname_pq: 1300_SAILDRONES_PHY
  add_derived_vars: True
  overwrite: True
  tmp_path:

Saildrones_BGC:
  db: Saildrones
  db_type: BGC
  db_codename: SAILDRONES
  input_path: /vortexfs1/share/boom/users/enrico.milanese/originalDatabases/Saildrones/
  outdir_pq: /vortexfs1/share/boom/users/enrico.milanese/myDatabases/1300_BGC_SAILDRONES/current/
  outdir_schema: ./schemas/Saildrones/
  fname_pq: 1300_SAILDRONES_BGC
  add_derived_vars: True
  overwrite: True
  tmp_path:

# OleanderXBT
OleanderXBT_PHY:
  db: OleanderXBT
  db_type: PHY
  db_codename: OLEANDER-XBT
  input_path: /vortexfs1/share/boom/users/enrico.milanese/originalDatabases/OleanderXBT/
  outdir_pq: /vortexfs1/share/boom/users/enrico.milanese/myDatabases/1401_PHY_OLEANDER-XBT/current/
  outdir_schema: ./schemas/OleanderXBT/
  fname_pq: 1401_OLEANDER-XBT_PHY
  add_derived_vars: False #note that this dataset only has temperature, so no derived vars cannot be computed probably
  overwrite: True
  tmp_path:

# Default relative path for demo data download
demo:
  download_path: ../demo/
